
version: '3.4'
services:
  app:
    build:
      context: ./app
    ports:
      - 8080:8080
    command: webapp
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"
  adminer:
    image: adminer
    ports:
      - "18080:8080"
    depends_on:
      - postgres
  notebook:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
volumes:
  postgres_data: {}
