
version: '3.4'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/:/etc/prometheus/
      - prometheus_data:/prometheus-data
  postgresql-exporter:
    # https://github.com/wrouesnel/postgres_exporter
    image: wrouesnel/postgres_exporter
    ports:
      - 9187:9187
    environment:
      # very insecure client connection
      - DATA_SOURCE_NAME=postgresql://test:test@postgres:5432/db?sslmode=disable
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
volumes:
  prometheus_data:
  grafana_data: