# USAGE:  docker-compose -f docker-compose.yml -f docker-compose.devel.yml ...
version: '3.4'
services:
  foo:
    image: foo:dev
    build:
      target: development
    volumes:
      - ./foo-package:/devel/foo-package