version: '3.4'
services:
  foo:
    image: foo:prod
    build:
      context: .
      dockerfile: foo-package/Dockerfile
      target: production
    ports:
      - '9081:8080'
    stdin_open: true
    tty: true