# USAGE:  docker-compose -f docker-compose.yml -f docker-compose.devel.yml ...
version: '3.4'
services:
  foo:
    image: foo:dev
    build:
      args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}
      # user: ${USER} # <<---- EXPLORE this
      target: development
    volumes:
      - ./foo-package:/home/scu/foo-package