version: '3.4'
services:
  test:
    build:
      context: .
      # target: production
    volumes:
      - .:/home/scu/mount
      - /var/run/docker.sock:/var/run/docker.sock
      #- /user/bin/docker:/usr/bin/docker
    command: /bin/bash