version: '3'
services:
  py3:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    volumes:
      - '.:/usr/src/app'
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8888:8888"
