version: '3.4'
services:
  jenkins:
    build:
      context: .
    volumes:
      #- jenkins-master-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # maps also executable!
      #- /usr/bin/docker:/usr/bin/docker
    ports:
      - 4040:4040
      - 8080:8080
